export const gruppenIds = {
    10:'Berufsübergreifender Lernbereich',
    11:'Aufgabenbereich I',
    20:'Berufsbezogener Lernbereich',
    21:'Aufgabenbereich II',
    25:'Berufsbezogener Bereich (Schwerpunkt)',
    30:'Differenzierungsbereich',
    31:'Aufgabenbereich III.1',
    32:'Aufgabenbereich III.2',
    33:'Aufgabenbereich III.3',
    40:'Berufspraktikum',
    60:'besondere Lernleistung',
    100:'Fremdsprachen',
    110:'Deutsch',
    200:'Naturwissenschaften',
    300:'Gesellschaftslehre',
    400:'Arbeitslehre',
    500:'Kunst und Musik',
    600:'Sport',
    700:'Mathematik',
    800:'Wahlpflichtbereich',
    900:'Religion',
    1000:'Zusätzliche Unterrichtsveranstaltungen',
    1100:'Angleichungskurse',
    1200:'Sprache',
    1300:'Sachunterricht',
    1400:'Förderunterricht',
    1500:'Vertiefungskurs',
    1600:'Projektkurs',
    1700:'Abschlussarbeit',
    1800:'Projektarbeit'
}